### ISSUE TITLE
Incompatibility with Better With Mods HC Strata

### ISSUE THREAD

**Issue by Laike-Endaril** [JackyyTV/Exchangers#57]
Better With Mods has a feature called HC Strata, which changes the mining level of stone as you dig deeper down.  Exchangers don't account for the change in mining level from this feature.

I spoke with one of the BWM mods shortly and he said...
`well
if you ask them tell them to call HarvestDropsEvent
and have a getHarvestLevel that is appropriate`

Ofc it seems the exchangers already have normal harvest levels, so I'm assuming it has more to do with just the call to HarvestDropsEvent?  Not that I know the internal workings of exchangers (just taking guesses).  I'm sure you'll have a better idea of how they interact.

**Comment by JackyyTV** [comment]
This is an interesting bug... I'll have to look further into that when I have time.

**Comment by JackyyTV** [comment]
I think I've fixed the issue, but I am not gonna release the update publicly yet since I've still got a few stuff to add for the final release. Here's an unreleased build, try it out and let me know if the issue has been resolved or not.
Download: [Click Here](http://jackyy.hk/stuff/minecraft/jars/Exchangers-1.12.2-2.9.jar)
You'll also need a new library mod called GunpowderLib for this build: [Click Here](https://www.curseforge.com/minecraft/mc-mods/gunpowderlib/files/2852431)

**Comment by Laike-Endaril** [comment]
Confirmed; this is fixed in the version posted.  I'll let you decide when to close this issue (in case you want it left open until you release a public jar)

**Comment by JackyyTV** [comment]
I'll leave this issue open until I have the new version ready for CurseForge since I still have a few things to add before I finalize the build.

**Comment by JackyyTV** [comment]
Fixed in [2.9](https://www.curseforge.com/minecraft/mc-mods/exchangers/files/2903998).
